"""final

Revision ID: 5bbc19db5f22
Revises: 1118e9937a9f
Create Date: 2020-12-15 15:02:16.711151

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5bbc19db5f22'
down_revision = '1118e9937a9f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('emotes', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('tweets', sa.Column('conversation_id', sa.Integer(), nullable=True))
    op.add_column('tweets', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('tweets', sa.Column('filter_level', sa.Integer(), nullable=True))
    op.add_column('tweets', sa.Column('in_reply_to_tweet_id', sa.Integer(), nullable=True))
    op.add_column('tweets', sa.Column('possibly_sensitive', sa.Boolean(), nullable=True))
    op.add_column('tweets', sa.Column('source_device', sa.String(), nullable=True))
    op.create_foreign_key(None, 'tweets', 'tweets', ['in_reply_to_tweet_id'], ['id'])
    op.create_foreign_key(None, 'tweets', 'tweets', ['conversation_id'], ['id'])
    op.add_column('users', sa.Column('is_admin', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_admin')
    op.drop_constraint(None, 'tweets', type_='foreignkey')
    op.drop_constraint(None, 'tweets', type_='foreignkey')
    op.drop_column('tweets', 'source_device')
    op.drop_column('tweets', 'possibly_sensitive')
    op.drop_column('tweets', 'in_reply_to_tweet_id')
    op.drop_column('tweets', 'filter_level')
    op.drop_column('tweets', 'created_at')
    op.drop_column('tweets', 'conversation_id')
    op.drop_column('emotes', 'created_at')
    # ### end Alembic commands ###
