"""Removed not null constraint on emote

Revision ID: 84156a715f43
Revises: 3044f797d920
Create Date: 2020-12-19 19:40:15.635938

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84156a715f43'
down_revision = '3044f797d920'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('emotes', 'author_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('emotes', 'author_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
