"""emote tweet joint

Revision ID: ed0cac44253c
Revises: 
Create Date: 2020-12-15 13:05:29.815090

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed0cac44253c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tweet_emote_joint',
    sa.Column('tweet_id', sa.Integer(), nullable=False),
    sa.Column('emote_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['emote_id'], ['emotes.id'], ),
    sa.ForeignKeyConstraint(['tweet_id'], ['tweets.id'], ),
    sa.PrimaryKeyConstraint('tweet_id', 'emote_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tweet_emote_joint')
    # ### end Alembic commands ###
