"""empty message

Revision ID: f9d310d76b31
Revises: 329bdefc3b47
Create Date: 2020-12-18 19:10:46.375527

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9d310d76b31'
down_revision = '329bdefc3b47'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('favourite_emotes_emote_id_fkey', 'favourite_emotes', type_='foreignkey')
    op.drop_constraint('favourite_emotes_user_id_fkey', 'favourite_emotes', type_='foreignkey')
    op.create_foreign_key(None, 'favourite_emotes', 'emotes', ['emote_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'favourite_emotes', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('tweet_emote_joint_emote_id_fkey', 'tweet_emote_joint', type_='foreignkey')
    op.drop_constraint('tweet_emote_joint_tweet_id_fkey', 'tweet_emote_joint', type_='foreignkey')
    op.create_foreign_key(None, 'tweet_emote_joint', 'tweets', ['tweet_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'tweet_emote_joint', 'emotes', ['emote_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tweet_emote_joint', type_='foreignkey')
    op.drop_constraint(None, 'tweet_emote_joint', type_='foreignkey')
    op.create_foreign_key('tweet_emote_joint_tweet_id_fkey', 'tweet_emote_joint', 'tweets', ['tweet_id'], ['id'])
    op.create_foreign_key('tweet_emote_joint_emote_id_fkey', 'tweet_emote_joint', 'emotes', ['emote_id'], ['id'])
    op.drop_constraint(None, 'favourite_emotes', type_='foreignkey')
    op.drop_constraint(None, 'favourite_emotes', type_='foreignkey')
    op.create_foreign_key('favourite_emotes_user_id_fkey', 'favourite_emotes', 'users', ['user_id'], ['id'])
    op.create_foreign_key('favourite_emotes_emote_id_fkey', 'favourite_emotes', 'emotes', ['emote_id'], ['id'])
    # ### end Alembic commands ###
