name: pipeline

on: push
    
jobs:
  test-suite:
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 2
        ports:
          # Maps tcp port 5432 on service to host
          - 5432:5432
    
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: setup python v3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ src/requirements.txt ]; then pip install -r src/requirements.txt; fi
          
      - name: setup environment variables for psycopg2 and run unittest
        run: |
          echo $DB_URI
          python -m unittest discover src/
        env:
          DB_URI: postgresql+psycopg2://postgres:postgres@localhost:5432/postgres